version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: weekly
    labels: ["dependencies"]
  
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    labels: ["dependencies"]
